# Generated by Django 4.2.8 on 2024-01-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_password_reset_sms_sent_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userpic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last password reset code sent at'),
        ),
    ]
