# Generated by Django 3.2.5 on 2021-07-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('kg', 'Kyrgyz')], default='en', max_length=10, verbose_name='Preferred language'),
        ),
    ]
