# Generated by Django 4.2.3 on 2023-11-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('moses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_candidate_confirm_pin',
            new_name='email_candidate_confirmation_pin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email_confirm_attempts',
            new_name='email_confirmation_attempts',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email_confirm_pin',
            new_name='email_confirmation_pin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number_candidate_confirm_pin',
            new_name='phone_number_candidate_confirmation_pin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number_confirm_attempts',
            new_name='phone_number_confirmation_attempts',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number_confirm_pin',
            new_name='phone_number_confirmation_pin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_phone_number_candidate_confirm_pin_sent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_phone_number_confirm_pin_sent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_phone_number_candidate_confirmation_pin_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_phone_number_confirmation_pin_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number_candidate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number candidate'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('site', 'phone_number'), name='one_phone_number_per_site'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('site', 'email'), name='one_email_per_site'),
        ),
    ]
