# Generated by Django 4.2.8 on 2024-01-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0002_remove_customuser_last_password_reset_sms_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_phone_number_candidate_confirmation_pin_sent',
            new_name='last_phone_number_confirmation_pins_sent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_phone_number_confirmation_pin_sent',
        ),
    ]
