# Generated by Django 4.2.9 on 2024-01-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0002_rename_last_phone_number_candidate_confirmation_pin_sent_customuser_last_phone_number_confirmation_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_confirmation_code_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last phone number confirmation code sent at'),
        ),
    ]
