# Generated by Django 4.2.7 on 2024-01-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0003_customuser_phone_number_confirmation_code_sms_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('kg', 'Kyrgyz')], default='en', max_length=10, verbose_name='Preferred language'),
        ),
    ]
