# Generated by Django 4.2.9 on 2024-01-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0004_alter_customuser_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=10, verbose_name='Preferred language'),
        ),
    ]
